smarthouse:
  mq:
  #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_regist_sms
    routingKey: regist
spring:
  application:
    name: sh-service-info-client
  data:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
server:
  port: 35001